//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmisSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmisSync.Properties.Resources", typeof(Properties_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About CmisSync.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a remote folder….
        /// </summary>
        internal static string AddARemoteFolder {
            get {
                return ResourceManager.GetString("AddARemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding synchronized folders to CmisSync.
        /// </summary>
        internal static string AddFolders {
            get {
                return ResourceManager.GetString("AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Folder.
        /// </summary>
        internal static string AddingFolder {
            get {
                return ResourceManager.GetString("AddingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse remote folder.
        /// </summary>
        internal static string BrowseRemoteFolder {
            get {
                return ResourceManager.GetString("BrowseRemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the local path of this repository:.
        /// </summary>
        internal static string ChangeRepoPath {
            get {
                return ResourceManager.GetString("ChangeRepoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync.
        /// </summary>
        internal static string CmisSync {
            get {
                return ResourceManager.GetString("CmisSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync creates a special folder on your computer where the documents are synchronized..
        /// </summary>
        internal static string CmisSyncCreates {
            get {
                return ResourceManager.GetString("CmisSyncCreates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to sync the existing local folder &quot;{0}&quot;?
        ///This could lead to a lot of conflict files!.
        /// </summary>
        internal static string ConfirmExistingLocalFolderText {
            get {
                return ResourceManager.GetString("ConfirmExistingLocalFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder &quot;{0}&quot; as sync target.
        /// </summary>
        internal static string ConfirmExistingLocalFolderTitle {
            get {
                return ResourceManager.GetString("ConfirmExistingLocalFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to server!
        ///Please check the given URL for misspelled host name.
        ///If the URL is correct, please contact your server administrator!.
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the local folder name.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable sync.
        /// </summary>
        internal static string DisableSync {
            get {
                return ResourceManager.GetString("DisableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents are automatically updated to reflect the latest changes from your colleagues, and your changes are sent to the server automatically too..
        /// </summary>
        internal static string DocumentsAre {
            get {
                return ResourceManager.GetString("DocumentsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable folder for synchronization.
        /// </summary>
        internal static string DoNotIgnoreFolder {
            get {
                return ResourceManager.GetString("DoNotIgnoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you trust this certificate?
        ///(Yes = Always, Cancel = Just Now).
        /// </summary>
        internal static string DoYouTrustTheCertificate {
            get {
                return ResourceManager.GetString("DoYouTrustTheCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty URL.
        /// </summary>
        internal static string EmptyURLNotAllowed {
            get {
                return ResourceManager.GetString("EmptyURLNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sync.
        /// </summary>
        internal static string EnableSync {
            get {
                return ResourceManager.GetString("EnableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the local folder where the documents are synchronized.
        /// </summary>
        internal static string EnterLocalFolderName {
            get {
                return ResourceManager.GetString("EnterLocalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Web address where the documents can be seen:.
        /// </summary>
        internal static string EnterWebAddress {
            get {
                return ResourceManager.GetString("EnterWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send some changes.
        /// </summary>
        internal static string FailedToSendSomeChanges {
            get {
                return ResourceManager.GetString("FailedToSendSomeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files up to date.
        /// </summary>
        internal static string FilesUpToDate {
            get {
                return ResourceManager.GetString("FilesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder already in the CmisSync root folder.
        /// </summary>
        internal static string FolderAlreadyExist {
            get {
                return ResourceManager.GetString("FolderAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} is already in use by {1}.
        /// </summary>
        internal static string FolderAlreadyInUse {
            get {
                return ResourceManager.GetString("FolderAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore folder on synchronization.
        /// </summary>
        internal static string IgnoreFolder {
            get {
                return ResourceManager.GetString("IgnoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync allows you to keep in sync with any CMIS-compliant enterprise server, and use your documents even when offline.
        ///
        ///It is like Dropbox for Enterprise Content Management!.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder name {0} is invalid. Special characters are not allowed..
        /// </summary>
        internal static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository name {0} contains illegal characters.
        /// </summary>
        internal static string InvalidRepoName {
            get {
                return ResourceManager.GetString("InvalidRepoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading aborted.
        /// </summary>
        internal static string LoadingStatusABORTED {
            get {
                return ResourceManager.GetString("LoadingStatusABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading ....
        /// </summary>
        internal static string LoadingStatusLOADING {
            get {
                return ResourceManager.GetString("LoadingStatusLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending ....
        /// </summary>
        internal static string LoadingStatusSTART {
            get {
                return ResourceManager.GetString("LoadingStatusSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A local folder with the same name already exist, please use a different name to prevent sync conflicts..
        /// </summary>
        internal static string LocalDirectoryExist {
            get {
                return ResourceManager.GetString("LocalDirectoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!
        ///Please check your user credentials and potentially the server URL..
        /// </summary>
        internal static string LoginFailedForbidden {
            get {
                return ResourceManager.GetString("LoginFailedForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run sync now.
        /// </summary>
        internal static string ManualSync {
            get {
                return ResourceManager.GetString("ManualSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may either take a short or a long time depending on the folder&apos;s size..
        /// </summary>
        internal static string MayTakeTime {
            get {
                return ResourceManager.GetString("MayTakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User %1 modified the file %2 at the same time as you..
        /// </summary>
        internal static string ModifiedSame {
            get {
                return ResourceManager.GetString("ModifiedSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given host name could not be found. Please check the host name and your internet connection..
        /// </summary>
        internal static string NameResolutionFailure {
            get {
                return ResourceManager.GetString("NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version ({0}) is available!.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the synchronized folder.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local folder.
        /// </summary>
        internal static string OpenLocalFolder {
            get {
                return ResourceManager.GetString("OpenLocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync is Open Source software. You are free to use, modify, and redistribute it under the GNU General Public License version 3 or later..
        /// </summary>
        internal static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMIS server found, but permission denied. Please check username/password..
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check for updates at CmisSync.com.
        /// </summary>
        internal static string PleaseCheckForUpdates {
            get {
                return ResourceManager.GetString("PleaseCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your documents are now being synchronized.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving changes….
        /// </summary>
        internal static string ReceivingChanges {
            get {
                return ResourceManager.GetString("ReceivingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the folder from synchronization.
        /// </summary>
        internal static string RemoveFolderFromSync {
            get {
                return ResourceManager.GetString("RemoveFolderFromSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disconnect this repository?  No files will be deleted from your system but they will no longer be synchronized..
        /// </summary>
        internal static string RemoveFolderFromSyncConfirm {
            get {
                return ResourceManager.GetString("RemoveFolderFromSyncConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove folder from synchronization?.
        /// </summary>
        internal static string RemoveSyncQuestion {
            get {
                return ResourceManager.GetString("RemoveSyncQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder from sync.
        /// </summary>
        internal static string RemoveSyncTitle {
            get {
                return ResourceManager.GetString("RemoveSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string ReportProblem {
            get {
                return ResourceManager.GetString("ReportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version..
        /// </summary>
        internal static string RunningLatestVersion {
            get {
                return ResourceManager.GetString("RunningLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate with the given server!
        ///Please check the protocol part of the given URL. Maybe your server is not capable to communicate over https.
        /// </summary>
        internal static string SendFailureHttps {
            get {
                return ResourceManager.GetString("SendFailureHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending changes….
        /// </summary>
        internal static string SendingChanges {
            get {
                return ResourceManager.GetString("SendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Tutorial.
        /// </summary>
        internal static string SkipTutorial {
            get {
                return ResourceManager.GetString("SkipTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, CmisSync can not find a CMIS server at this address.
        ///Please ask your server administrator for the CMIS endpoint URL.
        ///If you are sure about the address, open it in a browser and post
        ///the resulting XML on the cmissync forum..
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CmisSync to startup items.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status icon is here to help.
        /// </summary>
        internal static string StatusIcon {
            get {
                return ResourceManager.GetString("StatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync&apos;s status icon shows the syncing progress, and provides easy access to your folders..
        /// </summary>
        internal static string StatusIconShows {
            get {
                return ResourceManager.GetString("StatusIconShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch sync at CmisSync startup.
        /// </summary>
        internal static string SyncAtStartup {
            get {
                return ResourceManager.GetString("SyncAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sync &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing changes….
        /// </summary>
        internal static string SyncingChanges {
            get {
                return ResourceManager.GetString("SyncingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Interval.
        /// </summary>
        internal static string SyncInterval {
            get {
                return ResourceManager.GetString("SyncInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a trusted Connection. Please inform your server administrator..
        /// </summary>
        internal static string TrustFailure {
            get {
                return ResourceManager.GetString("TrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted Certificate.
        /// </summary>
        internal static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        internal static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository URL.
        /// </summary>
        internal static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CmisSync!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s happening next?.
        /// </summary>
        internal static string WhatsNext {
            get {
                return ResourceManager.GetString("WhatsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is your organization&apos;s server?.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to find this address.
        /// </summary>
        internal static string WhereToFind {
            get {
                return ResourceManager.GetString("WhereToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which remote folder do you want to sync?.
        /// </summary>
        internal static string Which {
            get {
                return ResourceManager.GetString("Which", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily add a new folder to synchronize, at any time..
        /// </summary>
        internal static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find them in your CmisSync folder..
        /// </summary>
        internal static string YouCanFind {
            get {
                return ResourceManager.GetString("YouCanFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version has been saved with a &apos;Conflict Copy&apos; suffix, please merge your important changes from it and then delete it..
        /// </summary>
        internal static string YourVersion {
            get {
                return ResourceManager.GetString("YourVersion", resourceCulture);
            }
        }
    }
}
