//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmisSync {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties_Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmisSync.Properties.Resources", typeof(Properties_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About CmisSync.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a remote folder….
        /// </summary>
        internal static string AddARemoteFolder {
            get {
                return ResourceManager.GetString("AddARemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding synchronized folders to CmisSync.
        /// </summary>
        internal static string AddFolders {
            get {
                return ResourceManager.GetString("AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding Folder.
        /// </summary>
        internal static string AddingFolder {
            get {
                return ResourceManager.GetString("AddingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse remote folder.
        /// </summary>
        internal static string BrowseRemoteFolder {
            get {
                return ResourceManager.GetString("BrowseRemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the local path of this repository:.
        /// </summary>
        internal static string ChangeRepoPath {
            get {
                return ResourceManager.GetString("ChangeRepoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CmisSync.
        /// </summary>
        internal static string CmisSync {
            get {
                return ResourceManager.GetString("CmisSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CmisSync creates a special folder on your computer where the documents are synchronized..
        /// </summary>
        internal static string CmisSyncCreates {
            get {
                return ResourceManager.GetString("CmisSyncCreates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to connect to server!
        ///Please check the given URL for misspelled host name.
        ///If the URL is correct, please contact your server administrator!.
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize the local folder name.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documents are automatically updated to reflect the latest changes from your colleagues, and your changes are sent to the server automatically too..
        /// </summary>
        internal static string DocumentsAre {
            get {
                return ResourceManager.GetString("DocumentsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable folder for synchronization.
        /// </summary>
        internal static string DoNotIgnoreFolder {
            get {
                return ResourceManager.GetString("DoNotIgnoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you trust this certificate?
        ///(Yes = Always, Cancel = Just Now).
        /// </summary>
        internal static string DoYouTrustTheCertificate {
            get {
                return ResourceManager.GetString("DoYouTrustTheCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty URL.
        /// </summary>
        internal static string EmptyURLNotAllowed {
            get {
                return ResourceManager.GetString("EmptyURLNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name for the local folder where the documents are synchronized.
        /// </summary>
        internal static string EnterLocalFolderName {
            get {
                return ResourceManager.GetString("EnterLocalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a Web address where the documents can be seen:.
        /// </summary>
        internal static string EnterWebAddress {
            get {
                return ResourceManager.GetString("EnterWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send some changes.
        /// </summary>
        internal static string FailedToSendSomeChanges {
            get {
                return ResourceManager.GetString("FailedToSendSomeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files up to date.
        /// </summary>
        internal static string FilesUpToDate {
            get {
                return ResourceManager.GetString("FilesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A folder already in the CmisSync root folder.
        /// </summary>
        internal static string FolderAlreadyExist {
            get {
                return ResourceManager.GetString("FolderAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore folder on synchronization.
        /// </summary>
        internal static string IgnoreFolder {
            get {
                return ResourceManager.GetString("IgnoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CmisSync allows you to keep in sync with any CMIS-compliant enterprise server, and use your documents even when offline.
        ///
        ///It is like Dropbox for Enterprise Content Management!.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder name is invalid. Special characters are not allowed..
        /// </summary>
        internal static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à loading ....
        /// </summary>
        internal static string LoadingStatusLOADING {
            get {
                return ResourceManager.GetString("LoadingStatusLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pending ....
        /// </summary>
        internal static string LoadingStatusSTART {
            get {
                return ResourceManager.GetString("LoadingStatusSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A local folder with the same name already exist, please use a different name..
        /// </summary>
        internal static string LocalDirectoryExist {
            get {
                return ResourceManager.GetString("LocalDirectoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login failed!
        ///Please check your user credentials and potentially the server URL..
        /// </summary>
        internal static string LoginFailedForbidden {
            get {
                return ResourceManager.GetString("LoginFailedForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run sync now.
        /// </summary>
        internal static string ManualSync {
            get {
                return ResourceManager.GetString("ManualSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This may either take a short or a long time depending on the folder&apos;s size..
        /// </summary>
        internal static string MayTakeTime {
            get {
                return ResourceManager.GetString("MayTakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User %1 modified the file %2 at the same time as you..
        /// </summary>
        internal static string ModifiedSame {
            get {
                return ResourceManager.GetString("ModifiedSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the synchronized folder.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open local folder.
        /// </summary>
        internal static string OpenLocalFolder {
            get {
                return ResourceManager.GetString("OpenLocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CmisSync is Open Source software. You are free to use, modify, and redistribute it under the GNU General Public License version 3 or later..
        /// </summary>
        internal static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause sync.
        /// </summary>
        internal static string PauseSync {
            get {
                return ResourceManager.GetString("PauseSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CMIS server found, but permission denied. Please check username/password..
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please check for updates at CmisSync.com.
        /// </summary>
        internal static string PleaseCheckForUpdates {
            get {
                return ResourceManager.GetString("PleaseCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your documents are now being synchronized.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receiving changes….
        /// </summary>
        internal static string ReceivingChanges {
            get {
                return ResourceManager.GetString("ReceivingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the folder from synchronization.
        /// </summary>
        internal static string RemoveFolderFromSync {
            get {
                return ResourceManager.GetString("RemoveFolderFromSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to disconnect this repository?  No files will be deleted from your system but they will no longer be synchronized..
        /// </summary>
        internal static string RemoveFolderFromSyncConfirm {
            get {
                return ResourceManager.GetString("RemoveFolderFromSyncConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report a problem.
        /// </summary>
        internal static string ReportProblem {
            get {
                return ResourceManager.GetString("ReportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume sync.
        /// </summary>
        internal static string ResumeSync {
            get {
                return ResourceManager.GetString("ResumeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to communicate with the given server!
        ///Please check the protocol part of the given URL. Maybe your server is not capable to communicate over https.
        /// </summary>
        internal static string SendFailureHttps {
            get {
                return ResourceManager.GetString("SendFailureHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending changes….
        /// </summary>
        internal static string SendingChanges {
            get {
                return ResourceManager.GetString("SendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings....
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip Tutorial.
        /// </summary>
        internal static string SkipTutorial {
            get {
                return ResourceManager.GetString("SkipTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, CmisSync can not find a CMIS server at this address.
        ///Please ask your server administrator for the CMIS endpoint URL.
        ///If you are sure about the address, open it in a browser and send
        ///the resulting XML to cmissync@aegif.jp.
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add CmisSync to startup items.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The status icon is here to help.
        /// </summary>
        internal static string StatusIcon {
            get {
                return ResourceManager.GetString("StatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CmisSync&apos;s status icon shows the syncing progress, and provides easy access to your folders..
        /// </summary>
        internal static string StatusIconShows {
            get {
                return ResourceManager.GetString("StatusIconShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch sync at CmisSync startup.
        /// </summary>
        internal static string SyncAtStartup {
            get {
                return ResourceManager.GetString("SyncAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not sync &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronization.
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syncing changes….
        /// </summary>
        internal static string SyncingChanges {
            get {
                return ResourceManager.GetString("SyncingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync Interval.
        /// </summary>
        internal static string SyncInterval {
            get {
                return ResourceManager.GetString("SyncInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to establish a trusted Connection. Please inform your server administrator..
        /// </summary>
        internal static string TrustFailure {
            get {
                return ResourceManager.GetString("TrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Untrusted Certificate.
        /// </summary>
        internal static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Log.
        /// </summary>
        internal static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository URL.
        /// </summary>
        internal static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to CmisSync!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What&apos;s happening next?.
        /// </summary>
        internal static string WhatsNext {
            get {
                return ResourceManager.GetString("WhatsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where is your organization&apos;s server?.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where to find this address.
        /// </summary>
        internal static string WhereToFind {
            get {
                return ResourceManager.GetString("WhereToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which remote folder do you want to sync?.
        /// </summary>
        internal static string Which {
            get {
                return ResourceManager.GetString("Which", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can easily add a new CMIS folder at any time..
        /// </summary>
        internal static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can find them in your CmisSync folder..
        /// </summary>
        internal static string YouCanFind {
            get {
                return ResourceManager.GetString("YouCanFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your version has been saved with a &apos;Conflict Copy&apos; suffix, please merge your important changes from it and then delete it..
        /// </summary>
        internal static string YourVersion {
            get {
                return ResourceManager.GetString("YourVersion", resourceCulture);
            }
        }
    }
}
