//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmisSync {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties_Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmisSync.Properties.Resources", typeof(Properties_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About A-SaaS Drive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a remote folder… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddARemoteFolder {
            get {
                return ResourceManager.GetString("AddARemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding synchronized folders to A-SaaS Drive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddFolders {
            get {
                return ResourceManager.GetString("AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddingFolder {
            get {
                return ResourceManager.GetString("AddingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse remote folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrowseRemoteFolder {
            get {
                return ResourceManager.GetString("BrowseRemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the local path of this repository: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeRepoPath {
            get {
                return ResourceManager.GetString("ChangeRepoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-SaaS Drive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmisSync {
            get {
                return ResourceManager.GetString("CmisSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-SaaS Drive creates a special folder on your computer where the documents are synchronized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmisSyncCreates {
            get {
                return ResourceManager.GetString("CmisSyncCreates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to sync the existing local folder &quot;{0}&quot;?
        ///This could lead to a lot of conflict files! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmExistingLocalFolderText {
            get {
                return ResourceManager.GetString("ConfirmExistingLocalFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected folder &quot;{0}&quot; as sync target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmExistingLocalFolderTitle {
            get {
                return ResourceManager.GetString("ConfirmExistingLocalFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to server!
        ///Please check the given URL for misspelled host name.
        ///If the URL is correct, please contact your server administrator! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customize the local folder name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documents are automatically updated to reflect the latest changes from your colleagues, and your changes are sent to the server automatically too. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DocumentsAre {
            get {
                return ResourceManager.GetString("DocumentsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable folder for synchronization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoNotIgnoreFolder {
            get {
                return ResourceManager.GetString("DoNotIgnoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you trust this certificate?
        ///(Yes = Always, Cancel = Just Now) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoYouTrustTheCertificate {
            get {
                return ResourceManager.GetString("DoYouTrustTheCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyURLNotAllowed {
            get {
                return ResourceManager.GetString("EmptyURLNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a name for the local folder where the documents are synchronized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterLocalFolderName {
            get {
                return ResourceManager.GetString("EnterLocalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a Web address where the documents can be seen: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterWebAddress {
            get {
                return ResourceManager.GetString("EnterWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to send some changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToSendSomeChanges {
            get {
                return ResourceManager.GetString("FailedToSendSomeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files up to date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilesUpToDate {
            get {
                return ResourceManager.GetString("FilesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A folder already in the A-SaaS Drive root folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderAlreadyExist {
            get {
                return ResourceManager.GetString("FolderAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory {0} is already in use by {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderAlreadyInUse {
            get {
                return ResourceManager.GetString("FolderAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore folder on synchronization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IgnoreFolder {
            get {
                return ResourceManager.GetString("IgnoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-SaaS Drive allows you to keep in sync with any CMIS-compliant enterprise server, and use your documents even when offline.
        ///
        ///It is like Dropbox for Enterprise Content Management! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder name {0} is invalid. Special characters are not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The repository name {0} contains illegal characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidRepoName {
            get {
                return ResourceManager.GetString("InvalidRepoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loading aborted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingStatusABORTED {
            get {
                return ResourceManager.GetString("LoadingStatusABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loading ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingStatusLOADING {
            get {
                return ResourceManager.GetString("LoadingStatusLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pending ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingStatusSTART {
            get {
                return ResourceManager.GetString("LoadingStatusSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A local folder with the same name already exist, please use a different name to prevent sync conflicts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocalDirectoryExist {
            get {
                return ResourceManager.GetString("LocalDirectoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login failed!
        ///Please check your user credentials and potentially the server URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginFailedForbidden {
            get {
                return ResourceManager.GetString("LoginFailedForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run sync now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ManualSync {
            get {
                return ResourceManager.GetString("ManualSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This may either take a short or a long time depending on the folder&apos;s size. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MayTakeTime {
            get {
                return ResourceManager.GetString("MayTakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User %1 modified the file %2 at the same time as you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModifiedSame {
            get {
                return ResourceManager.GetString("ModifiedSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given host name could not be found. Please check the host name and your internet connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameResolutionFailure {
            get {
                return ResourceManager.GetString("NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A newer version ({0}) is available! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the synchronized folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open local folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenLocalFolder {
            get {
                return ResourceManager.GetString("OpenLocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-SaaS Drive is Open Source software. You are free to use, modify, and redistribute it under the GNU General Public License version 3 or later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause sync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PauseSync {
            get {
                return ResourceManager.GetString("PauseSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CMIS server found, but permission denied. Please check username/password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check for updates at CmisSync.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseCheckForUpdates {
            get {
                return ResourceManager.GetString("PleaseCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your documents are now being synchronized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving changes… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReceivingChanges {
            get {
                return ResourceManager.GetString("ReceivingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove the folder from synchronization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveFolderFromSync {
            get {
                return ResourceManager.GetString("RemoveFolderFromSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to disconnect this repository?  No files will be deleted from your system but they will no longer be synchronized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveFolderFromSyncConfirm {
            get {
                return ResourceManager.GetString("RemoveFolderFromSyncConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to remove folder from synchronization? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveSyncQuestion {
            get {
                return ResourceManager.GetString("RemoveSyncQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove folder from sync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveSyncTitle {
            get {
                return ResourceManager.GetString("RemoveSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report a problem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportProblem {
            get {
                return ResourceManager.GetString("ReportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume sync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResumeSync {
            get {
                return ResourceManager.GetString("ResumeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are running the latest version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunningLatestVersion {
            get {
                return ResourceManager.GetString("RunningLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to communicate with the given server!
        ///Please check the protocol part of the given URL. Maybe your server is not capable to communicate over https に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendFailureHttps {
            get {
                return ResourceManager.GetString("SendFailureHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending changes… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendingChanges {
            get {
                return ResourceManager.GetString("SendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip Tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SkipTutorial {
            get {
                return ResourceManager.GetString("SkipTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry, A-SaaS Drive can not find a CMIS server at this address.
        ///Please ask your server administrator for the CMIS endpoint URL.
        ///If you are sure about the address, open it in a browser and post
        ///the resulting XML on the cmissync forum. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add A-SaaS Drive to startup items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The status icon is here to help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusIcon {
            get {
                return ResourceManager.GetString("StatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-SaaS Drive&apos;s status icon shows the syncing progress, and provides easy access to your folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusIconShows {
            get {
                return ResourceManager.GetString("StatusIconShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch sync at A-SaaS Drive startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncAtStartup {
            get {
                return ResourceManager.GetString("SyncAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not sync &quot;{0}&quot;: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syncing changes… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncingChanges {
            get {
                return ResourceManager.GetString("SyncingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncInterval {
            get {
                return ResourceManager.GetString("SyncInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to establish a trusted Connection. Please inform your server administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TrustFailure {
            get {
                return ResourceManager.GetString("TrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Untrusted Certificate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repository URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to A-SaaS Drive! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What&apos;s happening next? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhatsNext {
            get {
                return ResourceManager.GetString("WhatsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Where is your organization&apos;s server? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Where to find this address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhereToFind {
            get {
                return ResourceManager.GetString("WhereToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Which remote folder do you want to sync? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Which {
            get {
                return ResourceManager.GetString("Which", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can easily add a new folder to synchronize, at any time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can find them in your A-SaaS Drive folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YouCanFind {
            get {
                return ResourceManager.GetString("YouCanFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your version has been saved with a &apos;Conflict Copy&apos; suffix, please merge your important changes from it and then delete it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YourVersion {
            get {
                return ResourceManager.GetString("YourVersion", resourceCulture);
            }
        }
    }
}
